sonar.projectKey=AI-Studio-File-Stats
sonar.projectName=AI-Studio-File-Stats
sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=src/test/**/*.ts
sonar.exclusions=out/**,node_modules/**,.vscode-test/**,coverage/**,.scannerwork/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
